# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python-Hello-CICD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8"]

    steps:
    - uses: actions/checkout@v4
    - run: docker build . -t hello-test-deploy
    - run: echo "${{SECRETS.DOCKER_PASSWORD}}"| docker login --username ${{SECRETS.DOCKER_USER}} --password-stdin
    - run: docker push ghayassadaf/hello-cicd
