
name: Python-Hello-CICD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - run: echo "${{SECRETS.DOCKER_PASSWORD}}"| docker login --username ${{SECRETS.DOCKER_USER}} --password-stdin
    - run: docker build -t hello-cicd:latest .
    - run: docker push ghayassadaf/hello-cicd
